### ISSUE TITLE
Internal Server Error (500)

### ISSUE THREAD

**Issue by ylapshin** [gibus/RT-Extension-ConditionalCustomFields#1]
RT version 4.4.1
After installation and cleaning mason cache

**Comment by gibus** [comment]
Hummm I need more information to help... Is there something in your http server log?

**Comment by ylapshin** [comment]
[Thu Apr 20 15:58:26.005673 2017] [core:error] [pid 9006] [client 192.168.100.100:53161] End of script output before headers: rt-server.fcgi

**Comment by ylapshin** [comment]
[Thu Apr 20 16:05:41.824496 2017] [fcgid:warn] [pid 9007] (104)Connection reset by peer: [client 192.168.100.72:64770] mod_fcgid: error reading data from FastCGI server
[Thu Apr 20 16:05:41.824593 2017] [core:error] [pid 9007] [client 192.168.100.72:64770] End of script output before headers: rt-server.fcgi
[9401] [Thu Apr 20 13:05:43 2017] [critical]: Can't locate RT/Extension/ConditionalCustomFields.pm in @INC (you may need to install the RT::Extension::ConditionalCustomFields module) (@INC contains: /opt/rt4/sbin/../local/lib /opt/rt4/sbin/../lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /opt/rt4/sbin/../lib/RT.pm line 751. (/opt/rt4/sbin/../lib/RT.pm:390)
Can't locate RT/Extension/ConditionalCustomFields.pm in @INC (you may need to install the RT::Extension::ConditionalCustomFields module) (@INC contains: /opt/rt4/sbin/../local/lib /opt/rt4/sbin/../lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /opt/rt4/sbin/../lib/RT.pm line 751.
[Thu Apr 20 16:05:43.093597 2017] [fcgid:warn] [pid 9003] (104)Connection reset by peer: [client 192.168.100.72:64772] mod_fcgid: error reading data from FastCGI server, referer: https://rt-prod.vit-spb.ru/
[Thu Apr 20 16:05:43.093651 2017] [core:error] [pid 9003] [client 192.168.100.72:64772] End of script output before headers: rt-server.fcgi, referer: https://rt-prod.vit-spb.ru/

**Comment by gibus** [comment]
It seems that the extension is not installed in the correct directory, it should be inside /opt/rt4/local/plugins/ in your case (then, fullpath of the module file should be /opt/rt4/local/plugins/RT-Extension-ConditionalCustomFields/lib/RT/Extension/ConditionalCustomFields.pm ).

**Comment by ylapshin** [comment]
I do installation instructions correctly and twise on  two ubuntu servers. May be config parameter with correct path (if that exist)?

**Comment by ylapshin** [comment]
directory 'plugins' created on the root of the filesystem

**Comment by gibus** [comment]
that's it: this plugins directory should be moved under /opt/rt4/local/
