### ISSUE TITLE
Error under perl5 (revision 5 version 26 subversion 2)

### ISSUE THREAD

**Issue by tbrumm** [gibus/RT-Extension-ConditionalCustomFields#3]
[5674] [Mon Jun 25 06:29:03 2018] [error]: Error during compilation of /opt/rt4/local/plugins/RT-Extension-ConditionalCustomFields/html/Callbacks/RT-Extension-ConditionalCustomFields/Elements/ShowRecord/AfterValue:
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/^CustomField.{ <-- HERE ([^}]+)}/ at /opt/rt4/local/plugins/RT-Extension-ConditionalCustomFields/html/Callbacks/RT-Extension-ConditionalCustomFields/Elements/ShowRecord/AfterValue line 1.

**Comment by tbrumm** [comment]
Sorry, forgot. Fresh install of RT 4.4.2

**Comment by tbrumm** [comment]
OK, please close, fix is attached

**Comment by gibus** [comment]
I was about to reply, but you've been too fast :) I've merged your patch. Thanks!

It seems this warning appeared with Perl 5.22 http://search.cpan.org/dist/perl-5.22.0/pod/perldelta.pod#A_literal_%22%7B%22_should_now_be_escaped_in_a_pattern

**Comment by gibus** [comment]
Just for documentation, the warning was actually announced with Perl 5.16 and implemented since Perl 5.18: https://metacpan.org/pod/release/RJBS/perl-5.16.0/pod/perldelta.pod#Other-Future-Deprecations
