### ISSUE TITLE
Not working on all types of cf's

### ISSUE THREAD

**Issue by iacob28** [gibus/RT-Extension-ConditionalCustomFields#5]
Hi there,

I have an issues with this plugin on my rt platform. I want to make a custom field of type "Upload" to be condition by another custom field of "Select One Value" type, and it seems to not working. The Upload CF appear no matter what I am doing. Has anyone encountered this problem?

Thanks
![screenshot 2019-01-18 at 09 34 58](https://user-images.githubusercontent.com/16120714/51371979-6338d980-1b04-11e9-8626-2da24665212e.png)

**Comment by gibus** [comment]
Thanks for this report Iacob.

Indeed Image/Binary CFs had not been tested yet. HTML for editing these types of CFs is actually different and prevented RT-ConditionalCustomFields to hide them when condition is not met.

I've fixed this in 0.13 release which should appear on cpanmeta in a few minutes…

**Comment by iacob28** [comment]
Thank you, Gibus. It's working now !
