### ISSUE TITLE
Does not seem to work on multiline or wiki CFs

### ISSUE THREAD

**Issue by jmmcatee** [gibus/RT-Extension-ConditionalCustomFields#6]
Seems that any of our CustomFields that use a multiline text box or the wiki input are not hidden.

**Comment by gibus** [comment]
Thanks for this report. It's actually the very same kind of issue as #5. So it's quite easy to fix. If you 're 
in a hurry, you can apply the attached patch [0001-Fix-textarea-CF-conditionned-by.patch.zip](https://github.com/gibus/RT-Extension-ConditionalCustomFields/files/2789626/0001-Fix-textarea-CF-conditionned-by.patch.zip). I still have to write some unitary tests before including this patch in the next release…

**Comment by gibus** [comment]
OK the fix (with unitary tests) is now released on v.015, available on https://metacpan.org/pod/RT::Extension::ConditionalCustomFields

**Comment by jmmcatee** [comment]
This resolved our issue. Thank you so much for the quick fix.
